### PR TITLE
If HOST envvar is not set, use config.autoname

### PR DESCRIPTION
**Pull request by regular**
Hi @staltz I have a use case for specifying the desired name in the config. Ok for you?

### CODE REVIEW

**Comment by regular** [comment]
P.S: I tried to write a test, but scuttletest-bot has a race condition. both test pass individually, but not when run in the same test suite ...

**Comment by staltz** [comment]
@regular Can I make you a maintainer of this module?

**Comment by regular** [comment]
@staltz I'd welcome that. (yea, seems I need it more than you do :) )

**Comment by regular** [comment]
@staltz can you make me npm owner? Then I'll publish this.

**Comment by staltz** [comment]
Done!

**Comment by regular** [comment]
Thanks!

**Pull request merged**
